### ISSUE TITLE
"Not now" next to tab will suspend automatically doesn't work

### ISSUE THREAD

**Issue by xodotLBO** [gioxx/MarvellousSuspender#237] opened 2024-10-12 09:59 UTC
Please complete the following information when submitting a feature request or bug report.
 * Extension version: 7.1.6.2
 * Browser name & version: Chrome 129.0.6668.100 and Chrome 129.0.6668.101
 * Operating system & version: Windows 11 Pro x64

As described above, "Not now" as to temporarily not suspend the current tab does not work anymore

**Comment by Technetium1** [comment] 2024-10-12 15:42
Please close this as it is a duplicate of https://github.com/gioxx/MarvellousSuspender/issues/86

**Closed as duplicate** 2024-10-12 16:18 UTC
Labels: duplicate

**Comment by xodotLBO** [comment] 2024-10-12 16:34
> Please close this as it is a duplicate of #86

Its crazy that i literally searched 3 times and didn't find nothing lmfao. Thanks, Gio closed it.
