### ISSUE TITLE
Problems after Chrome 91 update 

### ISSUE THREAD

**Issue by reacap** [gioxx/MarvellousSuspender#112] opened 2021-05-25 22:50 UTC
* Extension version: 7.1.6.2
 * Browser name & version: chrome 91
 * Operating system & version: win 10 latest 

Weird behavior after chrome 91 update. Suspension sometimes has problems  with closing tabs (very slow or not closing at all , sites not on white list ) auto-resume bugs out and not working or takes too much time (with chrome option on in settings and without it too) 

Really hope it's just me , but check it out

**Comment by kogotex** [comment] 2021-05-26 05:34
Система аналогична.
Проблему подтверждаю.
Помогите!

**Comment by kogotex** [comment] 2021-05-26 05:35
The system is similar.
I confirm the problem.
Help!

**Comment by AlexWayfer** [comment] 2021-05-26 07:26
I have blank tabs:

![image](https://user-images.githubusercontent.com/6510020/119619554-cb9ed080-be0c-11eb-991c-c31dc83a0ebe.png)


As I see, the layout is here, but there is the `hide-initially` class for `body`. So, I guess, the problem is in scripts.

**Comment by TobySkarting** [comment] 2021-05-27 00:06
Temporary Solution:
Go to the extension menu to resume all tabs.
Backup your tabs.
Downgrade to 90 or older.

//
Update:
Weird. Soon after this comment it works as normal again.

**Comment by raisedintheusa** [comment] 2021-05-27 02:37
Also seeing the same issues.
Auto-resume is not being triggered when clicking on suspended tabs in the tab strip, but if I close a tab so it automatically switches to another tab that's suspended, then auto-resume is triggered.
Also, the "not now" after "tab will suspend automatically" in the context menu does not work.
Also, the current active tab that I have open and focused gets suspended after timeout as if it was an inactive tab, which never happened before, and it seems at times inactive tabs are not getting suspended after timeout.

**Comment by AlexWayfer** [comment] 2021-05-27 07:32
After downgrade I saw blank pages and could not load original with reload button. From Dev console I've got that there were `about:blank` pages. Firstly, I've loaded them via hitting `Enter` in address bar (`Ctrl+L` for its focus), lately I've just pressed "Unsuspend all tabs" from the extension icon menu.

**Comment by welovfree** [comment] 2021-05-28 02:53
I'm getting a blank page after the update to chrome 91, I confirm the issue.

**Comment by tripathi-abhishek** [comment] 2021-05-28 19:09
I confirm this issue as well. **A tested temporary workaround is "Unsuspend all suspended tabs" then "suspend them once again".**
Cant comment on losing any tabs, I have not lost any of them yet; restarting doesn't help.
Happened after the new update.

**OS:** Windows 10 Pro
**Chrome:** Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by baz357** [comment] 2021-05-29 14:43
I'm now scared to update Chrome to version 91...

**Comment by reacap** [comment] 2021-05-29 14:49
Tried the past revision of this extension before it was sold and it's the same issue too with chrome 91

**Comment by baz357** [comment] 2021-05-30 18:28
Others report the same issue at https://chrome.google.com/webstore/detail/the-marvellous-suspender/noogafoofpebimajpfpamcfhoaifemoa . @gioxx @sherkot: any chance to get a fixed version quickly?

Chrome crashed today, which caused the update to version 91, but for some reason TMS still works here. Weird (but good).

**Comment by baz357** [comment] 2021-05-30 18:40
> Others report the same issue at https://chrome.google.com/webstore/detail/the-marvellous-suspender/noogafoofpebimajpfpamcfhoaifemoa . @gioxx @sherkot: any chance to get a fixed version quickly?
> 
> Chrome crashed today, which caused the update to version 91, but for some reason TMS still works here. Weird (but good).

9 minutes later, TMS - for the first time ever - decided to suspend a tab while I was reading an article, scrolling down every x seconds.

**Comment by gioxx** [comment] 2021-05-30 19:00
Thanks for the reports guys, we will check soon.
@napolux can u give us a hand to check this issue and solve if possible?

**Comment by tuqqo** [comment] 2021-06-01 03:01
the only problem i got is that the plugin does not suspend any tabs anymore.

**Comment by Infinitay** [comment] 2021-06-03 17:48
Version 91.0.4472.77 (Official Build) (64-bit)

Same issue happened to me for the first time. Never experienced this before, and to my knowledge my Chrome has for the most part always been up-to-date.

**Comment by Technetium1** [comment] 2021-06-03 22:41
Since the update to the newest Chrome, I have only been intermittently able to suspend all tabs and unsuspend them after. A strange workaround is holding CTRL+TAB to cycle through all tabs, then unsuspending works as expected.

**Comment by welovfree** [comment] 2021-06-04 00:01
As a temporary solution: If you guys have the OneTab extension installed sending all suspended tabs to OneTab and restoring them will solve the issue and make the blank suspended tabs revert back to their normal state.

**Comment by macsunmood** [comment] 2021-06-04 10:54
What is the best workaround existing at the moment? Should I fully restart Chrome if it's begging for update?

**Comment by briantully** [comment] 2021-06-05 05:06
I started having this problem recently as well. Glad it's not just me!

For those smartly observing that the issue occurred just after the Chrome 91 update, I'd be curious to know what your TMS settings are for the "Apply Chrome's built-in memory-saving when suspending" option -- checked or unchecked? In other words, is anyone having this issue with this setting enabled/checked? If so, and it's consistent among us, maybe that points to a change in Chrome's built-in-memory-saving when suspending?

**Comment by denniskrol** [comment] 2021-06-05 05:08
The keyboard shortcut for 'Suspend/Unsuspend active tab' still works for unsuspending a 'broken' (white) tab.

**Comment by neviln** [comment] 2021-06-05 07:01
@briantully I had this issue and I had that option checked in the options.

To anyone else with this issue, I found an alternative fix that restored my tabs in their previously suspended states, but it requires you to have had SessionBuddy installed. I posted more details in issue #112 (https://github.com/gioxx/MarvellousSuspender/issues/121#issuecomment-855180586)

**Comment by reacap** [comment] 2021-06-05 07:01
@briantully I tested it with both option on and off and results are the same. 
Still problems regardless of Chrome's built-in-memory-saving

**Comment by baz357** [comment] 2021-06-05 19:50
I'm not sure if TMS plays a role or not, but I've had WAY more frequent Chrome crashes/ freezes since updating to version 91. :( Yesterday it happened with an uptime of <24 hours, which is extremely rare here.

**Comment by Technetium1** [comment] 2021-06-06 10:07
@baz357 I haven't gotten a single crash yet! You can get more information by checking here `chrome://crashes/`. This should help you determine whether it's to do with this extension.

**Comment by baz357** [comment] 2021-06-06 11:27
> @baz357 I haven't gotten a single crash yet! You can get more information by checking here `chrome://crashes/`. This should help you determine whether it's to do with this extension.

Thanks, never heard about chrome://crashes/ . Sadly, there's not much on that page, just "There are no recently reported crashes. Crashes that occurred while the crash reporting feature was disabled are not shown here." According to https://support.google.com/chrome/answer/96817?co=GENIE.Platform%3DDesktop&hl=en#zippy=%2Ccomputer , my Chrome is set up correctly for those crash reports (and I vaguely recall last year being asked if I wanted to send a crash report after a crash happened). Weird. :(

At least I've now disabled my least-loved extensions, hopefully my Chrome will be more stable again now. :)

**Comment by raisedintheusa** [comment] 2021-06-08 18:32
@briantully
Having Chrome's built-in memory-saving enabled results in a bunch of renderer processes being started. I found like 10 renderers running in the task manager, whereas with it disabled, there typically is just the one spare renderer process, so it kind of defeats the purpose of having an extension to help save ram. This happens with any extension that uses the native chrome discarding functionality, such as auto tab discard.

**Comment by reacap** [comment] 2021-06-09 21:52
Got chrome  91.0.4472.101 update 
Will see if problem still applies 

Edit - still the same issues

**Comment by dwandw** [comment] 2021-06-10 15:14
Could not get internalTabView for suspended tab

**Comment by fennelpollen** [comment] 2021-06-12 21:46
This problem occurs on two different computers I'm using (for the past two weeks or so). I noticed that this is also a workaround some might prefer: ctrl+w to close the tab, shift+ctrl+t to bring it back, now clicking the page works.

**Comment by baz357** [comment] 2021-06-13 12:00
> This problem occurs on two different computers I'm using (for the past two weeks or so). I noticed that this is also a workaround some might prefer: ctrl+w to close the tab, shift+ctrl+t to bring it back, now clicking the page works.

Sounds good, but did you use something like https://www.autohotkey.com/ to use Ctrl+T differently? Ctrl+T _opens_ a new tab here...

**Comment by Technetium1** [comment] 2021-06-13 20:05
@baz357 It seems you misunderstood. While **CTRL+T** opens a new tab, adding the shift modifier **CTRL+SHIFT+T** reopens the last closed tabs/windows.

---

I have Chrome Version 91.0.4472.101 and I'm now experiencing infrequent tab crashes. A tab reload seems to set everything straight.

If the entire browser starts to glitch you can use `chrome://restart` to reload your session as long as you don't have a setting to clear cookies/cache on exit.

**Comment by baz357** [comment] 2021-06-14 17:59
> @baz357 It seems you misunderstood. While **CTRL+T** opens a new tab, adding the shift modifier **CTRL+SHIFT+T** reopens the last closed tabs/windows.

Yes, thanks, I know about that, but I just realized that I misread when @fennelpollen wrote "ctrl+w to close the tab". Somehow I read that as "ctrl+t to close the tab"... I should get more sleep. :D

**Comment by baz357** [comment] 2021-06-14 18:01
> > @baz357 It seems you misunderstood. While **CTRL+T** opens a new tab, adding the shift modifier **CTRL+SHIFT+T** reopens the last closed tabs/windows.
> 
> Yes, thanks, I know about that, but I just realized that I misread when @fennelpollen wrote "ctrl+w to close the tab". Somehow I read that as "ctrl+t to close the tab"... I should get more sleep. :D

Ha! @fennelpollen DID write "ctrl+t to close the tab" originally. I read that in the notification email and didn't realize it was then changed here. :)

**Comment by PatrickL546** [comment] 2021-06-17 00:53
This should be fixed with chrome 91.0.4472.106 (June 14 update) and it is fixed for me. https://bugs.chromium.org/p/chromium/issues/detail?id=1216788

**Comment by AlexWayfer** [comment] 2021-06-17 08:24
I confirm, it's fixed in this Chrome version and this issue can be closed as external.

**Closed as completed** 2021-06-17 08:25 UTC
Labels: help wanted, to be investigated
