### ISSUE TITLE
Can't tell what the pages are at all when suspended

### ISSUE THREAD

**Issue by aushinia** [gioxx/MarvellousSuspender#165] opened 2022-03-15 19:16 UTC
Hi, 

As of today (March 15, 2022. UTC+8) when I opened Google Chrome (Version 99.0.4844.51 (Official Build) (64-bit)) with Win 7 64bit on my laptop (Lenovo Thinkpad X220), I found the extension has somehow edited some of it's design and function, and now when a tab is frozen, the original thumbnail and title is replaced with the extension's logo and all titles as "..." (see image below), making it very confusing for user to know which tab to wake. It also effects Tabs Outliner, another extention for tab managing, rendering all suspended sites not recognizable. It would be really appreciated if the original logo and title of the page could be kept so users will know what to look for!

![Screenshot 2022-03-16 01 58 32](https://user-images.githubusercontent.com/101668056/158454252-d8ac0b7d-5dd9-4010-bfaf-3aa00b9f0661.png)

Cheers,
Aushinia

**Comment by Masamune3210** [comment] 2022-03-15 21:03
Please search for already open issue reports before creating a new one, this is a duplicate of #161

**Closed as duplicate** 2022-04-03 17:08 UTC
Labels: duplicate
