### ISSUE TITLE
Alternate way to save current session

### ISSUE THREAD

**Issue by Pascal666** [gioxx/MarvellousSuspender#128] opened 2021-06-09 22:46 UTC
* Extension version: v7.1.6.2
 * Browser name & version: Google Chrome Version 90.0.4430.212 (Official Build) (64-bit)
 * Operating system & version: Microsoft Windows Version 10.0.19042.985

As far as I know, currently the only way to save the current session is via the Session Management tab in TMS Settings at chrome-extension://noogafoofpebimajpfpamcfhoaifemoa/history.html

Currently when I visit that tab there is no way to save my current session:
![image](https://user-images.githubusercontent.com/1330708/121438775-3f32f880-c94a-11eb-9bf4-5a39888f8b4b.png)

It would be nice if there was an alternate way to save the current session that could be used when this tab is malfunctioning.  Thank you.

**Comment by PatrickL546** [comment] 2021-06-10 01:03
I recommend Session Buddy. It automatically saves sessions up to 500 or manually save sessions and you can name them.

https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko?hl=en

![image](https://user-images.githubusercontent.com/75874561/121448477-bde95f00-c965-11eb-9106-f43a46097ad2.png)

**Comment by q00u** [comment] 2021-06-11 00:56
Be warned that I've lost a LOT of sleeping tabs since this broke, even with Session Buddy:

![2021-06-10 17_50_47-Current Session - Session Buddy](https://user-images.githubusercontent.com/892302/121614885-8be30600-ca14-11eb-8446-74d9d5cbbfef.png)

Restarting the browser with still-sleeping tabs might have done it (if the built-in session manager didn't restore them, then Session Buddy wouldn't record them; this is just conjecture on my part).

**Comment by PatrickL546** [comment] 2021-06-11 02:55
I'm not sure I'm quite getting what you're saying but those 1327 down to 668. Can't you just export the 1327 tabs, delete the chrome extension from the URL and import it back with the original URLs?

**Comment by PatrickL546** [comment] 2021-06-11 02:56
> Be warned that I've lost a LOT of sleeping tabs since this broke, even with Session Buddy:
> 
> ![2021-06-10 17_50_47-Current Session - Session Buddy](https://user-images.githubusercontent.com/892302/121614885-8be30600-ca14-11eb-8446-74d9d5cbbfef.png)
> 
> Restarting the browser with still-sleeping tabs might have done it (if the built-in session manager didn't restore them, then Session Buddy wouldn't record them; this is just conjecture on my part).

I'm not sure I'm quite getting what you're saying but those 1327 down to 668. Can't you just export the 1327 tabs, delete the chrome extension from the URL and import it back with the original URLs?

**Comment by q00u** [comment] 2021-06-11 07:09
I'm saying that if you still have TMS active, you can still silently lose tabs even while running Session Buddy.

**Comment by candrapersada** [comment] 2021-06-27 19:00
Alternative way to sync session tabs from browser to other browser using floccus or other extension when using The Great Suspenders?

**Comment by napolux** [comment] 2021-07-26 18:51
The issue is not clear, and is out of scope. Please reopen issue if you feel this can be integrated into TMS

**Closed as completed by napolux** 2021-07-26 18:51 UTC
Labels: wontfix
