### ISSUE TITLE
[Request] Resuming a tab doesn't scroll to the position it was saved at

### ISSUE THREAD

**Issue by Trip69** [gioxx/MarvellousSuspender#96] opened 2021-04-10 13:08 UTC
Please complete the following information when submitting a feature request or bug report.
 * Extension version:
 * Browser name & version:
 * Operating system & version:

And please also do a search for your request/bug before create a new one thanks!

v7.1.6.2
Version 89.0.4389.114 (Official Build) (64-bit)
Windows 10 Pro x64 Uptodate.

This extension used to return you to the place on the page you were when unsuspending, I doesn't seem to do that may more, It opens the page and leaves you at the top. Can the old functionality be restored, maybe as an option?

Thanks anyway for your get work, I find the ext extremely useful.

**Comment by gioxx** [comment] 2021-04-18 08:37
Please check this other report and tell me if it's your same problem: https://github.com/gioxx/MarvellousSuspender/issues/77

Thanks!
Giovanni

**Comment by Trip69** [comment] 2021-04-21 01:42
Could well be.

To reproduce, Go to google, search for anything. Scroll to the bottom of the page. open Inspect/network tab->Clear then suspend page Ctrl+shift+s and you'll see a butt load of network traffic.

Anyhow, when you unsuspend, the page is at the top. It used to be in the same position (the bottom in this case), It's really very useful not to lose your place in long message board posts.

**Comment by galfonso99** [comment] 2021-04-29 00:12
I had to downgrade to the previous version to regain this feature. If its totally a deal breaker for you I recommend you to do the same. I will make sure to upgrade to latest version once it is fixed. Cheers.

**Comment by Trip69** [comment] 2021-05-18 00:45
Getting bored waiting for a simple fix.....

**Comment by Technetium1** [comment] 2021-05-28 22:46
> Getting bored waiting for a simple fix.....

If it really is a simple fix feel free to submit a PR for review, but this should have been solved with https://github.com/gioxx/MarvellousSuspender/commit/4060cce3b6414915db19b1b617e6059c6793278d 😃

**Comment by sherkot** [comment] 2021-05-29 14:20
Fixed with https://github.com/gioxx/MarvellousSuspender/commit/4060cce3b6414915db19b1b617e6059c6793278d

**Closed as completed by sherkot** 2021-05-29 14:20 UTC

**Comment by Trip69** [comment] 2021-05-31 01:13
ffs. can you not do a simple test to see if it is fixed......? Open an message board like maybe the one here https://github.com/gioxx/MarvellousSuspender/issues/96 scroll to bottom (use the end key) then suspend [ctrl shif s] and reopen the tab and, its at the top. I know testers get paid a lot cause their job is boring asf but cumon

**Comment by gioxx** [comment] 2021-05-31 07:44
> 
> 
> ffs. can you not do a simple test to see if it is fixed......? Open an message board like maybe the one here #96 scroll to bottom (use the end key) then suspend [ctrl shif s] and reopen the tab and, its at the top. I know testers get paid a lot cause their job is boring asf but cumon

Ciao @Trip69, the problem is fixed on GitHub version of the addon, you have to wait the push of TMS 7.1.6.3 on Chrome Store if you use the "public & official version". Please be patient, take a look on this reply to know why 7.1.6.3 is not yet available on Chrome Store: https://github.com/gioxx/MarvellousSuspender/issues/86#issuecomment-851271379

Thank you for your understanding.

**Comment by Trip69** [comment] 2021-05-31 22:09
Ok, I am sorry. I have worked in dev and support and as and in this regard, end user. I appreciate you not flaming me for my comment, which were based on the topic being closed while running the latest chrome store app as you guessed the bug was still there. Apologies again, I'll stfu and wait for the push 🙂

Reagrds

________________________________
